
// CATEGORY
export const CREATE_CATEGORY="CREATE_CATEGORY"
export const CREATE_CATEGORY_RED="CREATE_CATEGORY_RED"

export const GET_CATEGORY="GET_CATEGORY"
export const GET_CATEGORY_RED="GET_CATEGORY_RED"

export const UPDATE_CATEGORY="UPDATE_CATEGORY"
export const UPDATE_CATEGORY_RED="UPDATE_CATEGORY_RED"

export const DELETE_CATEGORY="DELETE_CATEGORY"
export const DELETE_CATEGORY_RED="DELETE_CATEGORY_RED"

// BRAND
export const CREATE_BRAND="CREATE_BRAND"
export const CREATE_BRAND_RED="CREATE_BRAND_RED"

export const GET_BRAND="GET_BRAND"
export const GET_BRAND_RED="GET_BRAND_RED"

export const UPDATE_BRAND="UPDATE_BRAND"
export const UPDATE_BRAND_RED="UPDATE_BRAND_RED"

export const DELETE_BRAND="DELETE_BRAND"
export const DELETE_BRAND_RED="DELETE_BRAND_RED"

// CAR
export const CREATE_CAR="CREATE_CAR"
export const CREATE_CAR_RED="CREATE_CAR_RED"

export const GET_CAR="GET_CAR"
export const GET_CAR_RED="GET_CAR_RED"

export const UPDATE_CAR="UPDATE_CAR"
export const UPDATE_CAR_RED="UPDATE_CAR_RED"

export const DELETE_CAR="DELETE_CAR"
export const DELETE_CAR_RED="DELETE_CAR_RED"

// FEATURE
export const CREATE_FEATURE="CREATE_FEATURE"
export const CREATE_FEATURE_RED="CREATE_FEATURE_RED"

export const GET_FEATURE="GET_FEATURE"
export const GET_FEATURE_RED="GET_FEATURE_RED"

export const UPDATE_FEATURE="UPDATE_FEATURE"
export const UPDATE_FEATURE_RED="UPDATE_FEATURE_RED"

export const DELETE_FEATURE="DELETE_FEATURE"
export const DELETE_FEATURE_RED="DELETE_FEATURE_RED"

// SERVICE
export const CREATE_SERVICE="CREATE_SERVICE"
export const CREATE_SERVICE_RED="CREATE_SERVICE_RED"

export const GET_SERVICE="GET_SERVICE"
export const GET_SERVICE_RED="GET_SERVICE_RED"

export const UPDATE_SERVICE="UPDATE_SERVICE"
export const UPDATE_SERVICE_RED="UPDATE_SERVICE_RED"

export const DELETE_SERVICE="DELETE_SERVICE"
export const DELETE_SERVICE_RED="DELETE_SERVICE_RED"

// FAQ
export const CREATE_FAQ="CREATE_FAQ"
export const CREATE_FAQ_RED="CREATE_FAQ_RED"

export const GET_FAQ="GET_FAQ"
export const GET_FAQ_RED="GET_FAQ_RED"

export const UPDATE_FAQ="UPDATE_FAQ"
export const UPDATE_FAQ_RED="UPDATE_FAQ_RED"

export const DELETE_FAQ="DELETE_FAQ"
export const DELETE_FAQ_RED="DELETE_FAQ_RED"

// SETTING
export const CREATE_SETTING="CREATE_SETTING"
export const CREATE_SETTING_RED="CREATE_SETTING_RED"

export const GET_SETTING="GET_SETTING"
export const GET_SETTING_RED="GET_SETTING_RED"

export const UPDATE_SETTING="UPDATE_SETTING"
export const UPDATE_SETTING_RED="UPDATE_SETTING_RED"

export const DELETE_SETTING="DELETE_SETTING"
export const DELETE_SETTING_RED="DELETE_SETTING_RED"

// BOOKING
export const CREATE_BOOKING="CREATE_BOOKING"
export const CREATE_BOOKING_RED="CREATE_BOOKING_RED"

export const GET_BOOKING="GET_BOOKING"
export const GET_BOOKING_RED="GET_BOOKING_RED"

export const UPDATE_BOOKING="UPDATE_BOOKING"
export const UPDATE_BOOKING_RED="UPDATE_BOOKING_RED"

export const DELETE_BOOKING="DELETE_BOOKING"
export const DELETE_BOOKING_RED="DELETE_BOOKING_RED"

// TESTIMONIAL
export const CREATE_TESTIMONIAL="CREATE_TESTIMONIAL"
export const CREATE_TESTIMONIAL_RED="CREATE_TESTIMONIAL_RED"

export const GET_TESTIMONIAL="GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED="GET_TESTIMONIAL_RED"

export const UPDATE_TESTIMONIAL="UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_RED="UPDATE_TESTIMONIAL_RED"

export const DELETE_TESTIMONIAL="DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED="DELETE_TESTIMONIAL_RED"

// CONTACTUS
export const CREATE_CONTACTUS="CREATE_CONTACTUS"
export const CREATE_CONTACTUS_RED="CREATE_CONTACTUS_RED"

export const GET_CONTACTUS="GET_CONTACTUS"
export const GET_CONTACTUS_RED="GET_CONTACTUS_RED"

export const UPDATE_CONTACTUS="UPDATE_CONTACTUS"
export const UPDATE_CONTACTUS_RED="UPDATE_CONTACTUS_RED"

export const DELETE_CONTACTUS="DELETE_CONTACTUS"
export const DELETE_CONTACTUS_RED="DELETE_CONTACTUS_RED"

// NEWSLETTER
export const CREATE_NEWSLETTER="CREATE_NEWSLETTER"
export const CREATE_NEWSLETTER_RED="CREATE_NEWSLETTER_RED"

export const GET_NEWSLETTER="GET_NEWSLETTER"
export const GET_NEWSLETTER_RED="GET_NEWSLETTER_RED"

export const UPDATE_NEWSLETTER="UPDATE_NEWSLETTER"
export const UPDATE_NEWSLETTER_RED="UPDATE_NEWSLETTER_RED"

export const DELETE_NEWSLETTER="DELETE_NEWSLETTER"
export const DELETE_NEWSLETTER_RED="DELETE_NEWSLETTER_RED"

// USER
export const CREATE_USER="CREATE_USER"
export const CREATE_USER_RED="CREATE_USER_RED"

export const GET_USER="GET_USER"
export const GET_USER_RED="GET_USER_RED"

export const UPDATE_USER="UPDATE_USER"
export const UPDATE_USER_RED="UPDATE_USER_RED"

export const DELETE_USER="DELETE_USER"
export const DELETE_USER_RED="DELETE_USER_RED"